shell.run("delete floorer.lua")
shell.run("delete item_provider.lua")
shell.run("delete update.lua")
shell.run("delete pe_craft.lua")
shell.run("delete rc_rec.lua")
shell.run("delete rc_driver.lua")

shell.run("wget https://raw.githubusercontent.com/michaelperino/cc-scripts/master/update.lua")
shell.run("wget https://raw.githubusercontent.com/michaelperino/cc-scripts/master/floorer.lua")
shell.run("wget https://raw.githubusercontent.com/michaelperino/cc-scripts/master/item_provider.lua")
shell.run("wget https://raw.githubusercontent.com/michaelperino/cc-scripts/master/pe_craft.lua")
shell.run("wget https://raw.githubusercontent.com/michaelperino/cc-scripts/master/rc_rec.lua")
shell.run("wget https://raw.githubusercontent.com/michaelperino/cc-scripts/master/rc_driver.lua")
